#Requires -Version 5.1
<#
.SYNOPSIS
    Windows equivalent of setup.sh for claude-config.

.DESCRIPTION
    Symlinks commands, rules, agents, skills, and templates into a project's
    .claude/ directory. Creates settings.local.json on first run.
    Requires Developer Mode OR running as Administrator to create symlinks.

.EXAMPLE
    .\setup.ps1 C:\projects\my-app
    .\setup.ps1 C:\projects\my-app -Force
    .\setup.ps1 C:\projects\my-app -Add rule
    .\setup.ps1 C:\projects\my-app -Add rule security.md
    .\setup.ps1 C:\projects\my-app -Remove command op.md
    .\setup.ps1 C:\projects\my-app -Remove
    .\setup.ps1 -List
    .\setup.ps1 -List rule
    .\setup.ps1 -Config
#>

$ErrorActionPreference = 'Stop'
$SCRIPT_DIR = $PSScriptRoot

# ---------- Output helpers ----------
function log    { param([string]$msg) Write-Host "v $msg" -ForegroundColor Green }
function warn   { param([string]$msg) Write-Host "! $msg" -ForegroundColor Yellow }
function err    { param([string]$msg) Write-Host "x $msg" -ForegroundColor Red }
function info   { param([string]$msg) Write-Host "> $msg" -ForegroundColor Cyan }
function header { param([string]$msg) Write-Host "`n$msg" -ForegroundColor White }

# ---------- Usage ----------
function Show-Usage {
    Write-Host @"

Usage:
  .\setup.ps1 <project-path> [-Force]
  .\setup.ps1 <project-path> -Add <type> [name]
  .\setup.ps1 <project-path> -Remove [type] [name]
  .\setup.ps1 -List [type]
  .\setup.ps1 -Config

Setup (default):
  Symlinks all commands and templates into the project's .claude/ directory.
  Creates settings.local.json on first run (project config + API keys).

Add extras:
  -Add rule [name]       Add one or all rules
  -Add agent [name]      Add one or all agents
  -Add skill [name]      Add one or all skills
  -Add command [name]    Add one or all commands
  -List [type]           List available items (commands, rules, agents, skills)
  -Config                Interactive wizard to configure defaults.conf

Remove:
  -Remove                Remove all symlinks
  -Remove rule [name]    Remove one or all rules
  -Remove agent [name]   Remove one or all agents
  -Remove skill [name]   Remove one or all skills
  -Remove command [name] Remove one or all commands

Options:
  -Force                 Replace existing files with symlinks

Examples:
  .\setup.ps1 C:\projects\my-app
  .\setup.ps1 C:\projects\my-app -Force
  .\setup.ps1 C:\projects\my-app -Add rule security.md
  .\setup.ps1 C:\projects\my-app -Add rule
  .\setup.ps1 C:\projects\my-app -Add agent code-reviewer.md
  .\setup.ps1 C:\projects\my-app -Remove command op.md
  .\setup.ps1 C:\projects\my-app -Remove

"@
    exit 1
}

# ---------- Warn if symlinks unavailable ----------
function Warn-SymlinkCapability {
    if (Test-CanSymlink) { return }
    Write-Host @"

NOTE: Symlinks unavailable - files will be copied instead.
  To enable symlinks (so edits sync back to claude-config):
    - Sign out and back in after enabling Developer Mode, OR
    - Run PowerShell as Administrator
  Then rerun: .\setup.ps1 <path> -Force

"@ -ForegroundColor Yellow
}

# ---------- Read defaults.conf (bash array format) ----------
function Read-DefaultsConf {
    $conf = @{
        COMMANDS         = @()
        RULES            = @()
        AGENTS           = @()
        SKILLS           = @()
        TEMPLATES        = @()
        INSTALL_SETTINGS = $false
    }

    $confFile = Join-Path $SCRIPT_DIR 'defaults.conf'
    if (-not (Test-Path $confFile)) { return $conf }

    foreach ($line in Get-Content $confFile) {
        $line = $line.Trim()
        if ($line -match '^#' -or $line -eq '') { continue }

        if ($line -match '^(\w+)=(.*)$') {
            $key = $Matches[1]
            $val = $Matches[2].Trim()

            switch -Regex ($val) {
                '^\(all\)$'    { $conf[$key] = @('all') }
                '^\(\)$'       { $conf[$key] = @() }
                '^true$'       { $conf[$key] = $true }
                '^false$'      { $conf[$key] = $false }
                default {
                    # Parse ("item1.md" "item2.md") or (item1.md item2.md)
                    $items = [regex]::Matches($val, '"([^"]+)"') | ForEach-Object { $_.Groups[1].Value }
                    if ($items.Count -eq 0) {
                        $items = [regex]::Matches($val, '\(([^)]+)\)') | ForEach-Object {
                            $_.Groups[1].Value -split '\s+' | Where-Object { $_ -ne '' }
                        }
                    }
                    $conf[$key] = @($items)
                }
            }
        }
    }
    return $conf
}

# ---------- Write defaults.conf (bash array format, shared with setup.sh) ----------
function Write-DefaultsConf {
    param(
        [hashtable]$Conf
    )

    $lines = @('# Generated by: .\setup.ps1 -Config', '')

    foreach ($key in @('COMMANDS', 'RULES', 'AGENTS', 'SKILLS', 'TEMPLATES')) {
        $val = $Conf[$key]
        if ($null -eq $val -or $val.Count -eq 0) {
            $lines += "${key}=()"
        } elseif ($val[0] -eq 'all') {
            $lines += "${key}=(all)"
        } else {
            $quoted = ($val | ForEach-Object { "`"$_`"" }) -join ' '
            $lines += "${key}=($quoted)"
        }
        $lines += ''
    }

    $settingsVal = if ($Conf['INSTALL_SETTINGS'] -eq $true) { 'true' } else { 'false' }
    $lines += "INSTALL_SETTINGS=$settingsVal"

    Set-Content -Path (Join-Path $SCRIPT_DIR 'defaults.conf') -Value $lines -Encoding UTF8
}

# ---------- Ensure entry in .gitignore ----------
function Add-GitIgnore {
    param([string]$ProjectPath, [string]$FilePath)

    $gitignore = Join-Path $ProjectPath '.gitignore'
    # Convert to relative path with forward slashes (git convention)
    $rel = $FilePath.Replace($ProjectPath, '').TrimStart('\', '/').Replace('\', '/')

    if (Test-Path $gitignore) {
        $existing = Get-Content $gitignore
        if ($existing -contains $rel) { return }
    }
    Add-Content -Path $gitignore -Value $rel
}

# ---------- Test symlink capability (cached) ----------
$script:CanSymlink = $null
function Test-CanSymlink {
    if ($null -ne $script:CanSymlink) { return $script:CanSymlink }
    try {
        $tmp = Join-Path ([System.IO.Path]::GetTempPath()) "claude_symlink_test_$PID"
        $null = New-Item -ItemType SymbolicLink -Path $tmp -Target $SCRIPT_DIR -Force -ErrorAction Stop
        Remove-Item $tmp -Force
        $script:CanSymlink = $true
    } catch {
        $script:CanSymlink = $false
    }
    return $script:CanSymlink
}

# ---------- Create symlink (falls back to copy if not privileged) ----------
# Returns $true if file was installed, $false if skipped.
function New-SymlinkFile {
    param(
        [string]$Src,
        [string]$Dest,
        [bool]$Force = $false
    )

    # Already linked correctly?
    if (Test-Path $Dest -PathType Leaf) {
        $item = Get-Item $Dest -Force
        if ($item.LinkType -eq 'SymbolicLink' -and $item.Target -eq $Src) {
            return $false
        }
    }

    # Existing non-symlink file
    if (Test-Path $Dest) {
        $item = Get-Item $Dest -Force
        $isLink = $item.LinkType -eq 'SymbolicLink'

        if (-not $isLink) {
            if ($Force) {
                Remove-Item $Dest -Force
            } else {
                $answer = Read-Host "  $(Split-Path $Dest -Leaf) exists. Replace? [y/N]"
                if ($answer -notmatch '^[Yy]') {
                    warn "Skipped: $(Split-Path $Dest -Leaf)"
                    return $false
                }
                Remove-Item $Dest -Force
            }
        } else {
            Remove-Item $Dest -Force
        }
    }

    if (Test-CanSymlink) {
        $null = New-Item -ItemType SymbolicLink -Path $Dest -Target $Src -Force
    } else {
        # Symlinks not available yet (need new login after enabling Developer Mode).
        # Copy the file instead — rerun with -Force after restarting to upgrade to symlinks.
        Copy-Item $Src $Dest -Force
    }
    return $true
}

# ---------- Create settings.local.json ----------
function New-LocalSettings {
    param([string]$ProjectPath)

    $target        = Join-Path $ProjectPath '.claude'
    $null = New-Item $target -ItemType Directory -Force
    $localSettings = Join-Path $target 'settings.local.json'

    # Ensure gitignored
    $gitignore = Join-Path $ProjectPath '.gitignore'
    if (Test-Path $gitignore) {
        if (-not (Select-String -Path $gitignore -Pattern 'settings\.local\.json' -Quiet)) {
            Add-Content $gitignore '.claude/settings.local.json'
            log "Added settings.local.json to .gitignore"
        }
    } else {
        Set-Content $gitignore '.claude/settings.local.json'
        log "Created .gitignore with settings.local.json"
    }

    if (Test-Path $localSettings) {
        $json = Get-Content $localSettings -Raw | ConvertFrom-Json
        if ($json.env) {
            warn "settings.local.json already exists - skipping"
            return
        }
        warn "settings.local.json exists but missing env section"
    }

    header "Create settings.local.json env"
    Write-Host "  Project config and API keys (gitignored).`n"

    $opBaseUrl   = Read-Host "OpenProject base URL"
    $opSlug      = Read-Host "OpenProject project slug"
    $ghRepo      = Read-Host "GitHub org/repo"
    $baseBranch  = Read-Host "Base branch [develop]"
    if (-not $baseBranch) { $baseBranch = 'develop' }
    $apiKey      = Read-Host "OpenProject API key"

    $envObj = [ordered]@{
        OP_BASE_URL          = $opBaseUrl
        OP_PROJECT_SLUG      = $opSlug
        GITHUB_ORG_REPO      = $ghRepo
        BASE_BRANCH          = $baseBranch
        OPENPROJECT_API_KEY  = $apiKey
    }

    if (Test-Path $localSettings) {
        $existing = Get-Content $localSettings -Raw | ConvertFrom-Json
        # Add env key to existing object
        $existing | Add-Member -NotePropertyName 'env' -NotePropertyValue $envObj -Force
        $existing | ConvertTo-Json -Depth 5 | Set-Content $localSettings -Encoding UTF8
        log "Added env to existing settings.local.json"
    } else {
        [ordered]@{ env = $envObj } | ConvertTo-Json -Depth 5 | Set-Content $localSettings -Encoding UTF8
        log "Created settings.local.json"
    }
}

# ---------- Normalize type name to plural ----------
function Get-TypeDir {
    param([string]$Type)
    switch ($Type) {
        { $_ -in 'rule',  'rules'   } { return 'rules'    }
        { $_ -in 'agent', 'agents'  } { return 'agents'   }
        { $_ -in 'command','commands'} { return 'commands' }
        { $_ -in 'skill', 'skills'  } { return 'skills'   }
        default { return $Type }
    }
}

# ---------- Install items of a type ----------
function Install-Type {
    param(
        [string]$ProjectPath,
        [string]$TypeDir,      # already normalized plural
        [string]$Name = '',
        [bool]$Force = $false
    )

    $target = Join-Path $ProjectPath '.claude'
    $srcDir = Join-Path $SCRIPT_DIR $TypeDir

    if ($TypeDir -eq 'skills') {
        if ($Name) {
            $skillDir = Join-Path $srcDir $Name
            if (-not (Test-Path $skillDir -PathType Container)) {
                err "Skill not found: $Name"; return
            }
            $destSkill = Join-Path $target "skills\$Name"
            $null = New-Item $destSkill -ItemType Directory -Force

            Get-ChildItem $skillDir -Recurse -File | ForEach-Object {
                $rel  = $_.FullName.Substring($skillDir.Length).TrimStart('\')
                $dest = Join-Path $destSkill $rel
                $null = New-Item (Split-Path $dest) -ItemType Directory -Force
                if (New-SymlinkFile $_.FullName $dest $Force) {
                    Add-GitIgnore $ProjectPath $dest
                }
            }
            log "Installed skill: $Name"
        } else {
            Get-ChildItem $srcDir -Directory | ForEach-Object {
                Install-Type $ProjectPath 'skills' $_.Name $Force
            }
        }
        return
    }

    $targetSubdir = Join-Path $target $TypeDir
    $null = New-Item $targetSubdir -ItemType Directory -Force

    if ($Name) {
        $src = Join-Path $srcDir $Name
        if (-not (Test-Path $src -PathType Leaf)) {
            err "$TypeDir not found: $Name"; return
        }
        $dest = Join-Path $targetSubdir $Name
        if (New-SymlinkFile $src $dest $Force) {
            Add-GitIgnore $ProjectPath $dest
            log "Installed $TypeDir`: $Name"
        }
    } else {
        # Top-level .md files
        Get-ChildItem $srcDir -Filter '*.md' -File | ForEach-Object {
            $dest = Join-Path $targetSubdir $_.Name
            if (New-SymlinkFile $_.FullName $dest $Force) {
                Add-GitIgnore $ProjectPath $dest
                log "Installed $TypeDir`: $($_.Name)"
            }
        }
        # Subdirectories (e.g. rules/typescript/)
        Get-ChildItem $srcDir -Directory | ForEach-Object {
            $sub = $_
            $subDest = Join-Path $targetSubdir $sub.Name
            $null = New-Item $subDest -ItemType Directory -Force
            Get-ChildItem $sub.FullName -Filter '*.md' -File | ForEach-Object {
                $dest = Join-Path $subDest $_.Name
                if (New-SymlinkFile $_.FullName $dest $Force) {
                    Add-GitIgnore $ProjectPath $dest
                    log "Installed $TypeDir`: $($sub.Name)/$($_.Name)"
                }
            }
        }
    }
}

# ---------- Remove items ----------
function Remove-Items {
    param(
        [string]$ProjectPath,
        [string]$TypeDir = '',
        [string]$Name    = ''
    )

    $target = Join-Path $ProjectPath '.claude'

    if (-not $TypeDir) {
        header "Removing all symlinks from $target"
        $count = 0
        foreach ($dir in @('rules','agents','commands','skills','templates')) {
            $d = Join-Path $target $dir
            if (-not (Test-Path $d)) { continue }
            Get-ChildItem $d -Recurse -File | Where-Object { $_.LinkType -eq 'SymbolicLink' } | ForEach-Object {
                Remove-Item $_.FullName -Force
                info "Removed: $($_.FullName.Replace($target + '\', ''))"
                $count++
            }
        }
        $ghDir = Join-Path $ProjectPath '.github'
        if (Test-Path $ghDir) {
            Get-ChildItem $ghDir -Recurse -File | Where-Object { $_.LinkType -eq 'SymbolicLink' } | ForEach-Object {
                Remove-Item $_.FullName -Force
                info "Removed: .github\$($_.Name)"
                $count++
            }
        }
        $settingsJson = Join-Path $target 'settings.json'
        if (Test-Path $settingsJson) { Remove-Item $settingsJson -Force; $count++ }
        log "Removed $count file(s). Run setup.ps1 again to reinstall."
        return
    }

    if ($Name) {
        if ($TypeDir -eq 'skills') {
            $skillDir = Join-Path $target "skills\$Name"
            if (Test-Path $skillDir) {
                Remove-Item $skillDir -Recurse -Force
                log "Removed skill: $Name"
            } else {
                warn "Skill not found: $Name"
            }
        } else {
            $dest = Join-Path $target "$TypeDir\$Name"
            if (Test-Path $dest) {
                Remove-Item $dest -Force
                log "Removed $TypeDir`: $Name"
            } else {
                warn "$TypeDir not found: $Name"
            }
        }
    } else {
        $dir = Join-Path $target $TypeDir
        if (Test-Path $dir) {
            $links = Get-ChildItem $dir -Recurse -File | Where-Object { $_.LinkType -eq 'SymbolicLink' }
            $links | ForEach-Object { Remove-Item $_.FullName -Force }
            log "Removed $($links.Count) $TypeDir symlink(s)"
        } else {
            warn "No $TypeDir installed"
        }
    }
}

# ---------- Clean stale symlinks ----------
function Clear-StaleSymlinks {
    param([string]$Target)

    $stale = 0
    foreach ($dir in @('rules','agents','commands','skills','templates')) {
        $d = Join-Path $Target $dir
        if (-not (Test-Path $d)) { continue }
        Get-ChildItem $d -Recurse -File | Where-Object { $_.LinkType -eq 'SymbolicLink' } | ForEach-Object {
            $linkTarget = $_.Target
            if (-not (Test-Path $linkTarget)) {
                Remove-Item $_.FullName -Force
                warn "Removed stale: $($_.FullName.Replace($Target + '\', ''))"
                $stale++
            }
        }
    }
    if ($stale -gt 0) { log "Cleaned $stale stale symlink(s)" }
}

# ---------- Default install ----------
function Install-Default {
    param([string]$ProjectPath, [bool]$Force = $false, [bool]$SkipSettings = $false)

    $target = Join-Path $ProjectPath '.claude'

    # Load or create defaults.conf
    $confFile = Join-Path $SCRIPT_DIR 'defaults.conf'
    if (-not (Test-Path $confFile)) {
        Copy-Item (Join-Path $SCRIPT_DIR 'defaults.conf.example') $confFile
        log "Created defaults.conf from example"
    }
    $conf = Read-DefaultsConf

    if (-not $SkipSettings) { New-LocalSettings $ProjectPath }
    $null = New-Item $target -ItemType Directory -Force
    Clear-StaleSymlinks $target

    header "Installing to $target"

    # settings.json (copied, not symlinked)
    $settingsDest = Join-Path $target 'settings.json'
    $settingsSrc  = Join-Path $SCRIPT_DIR 'settings.json'
    if ($conf['INSTALL_SETTINGS'] -ne $true) {
        info "Skipping settings.json (INSTALL_SETTINGS=false in defaults.conf)"
    } elseif ((Test-Path $settingsDest) -and -not ((Get-Item $settingsDest -Force).LinkType -eq 'SymbolicLink')) {
        if (-not $Force) {
            $srcHash  = (Get-FileHash $settingsSrc).Hash
            $destHash = (Get-FileHash $settingsDest).Hash
            if ($srcHash -ne $destHash) {
                $answer = Read-Host "  settings.json exists and differs. Replace? [y/N]"
                if ($answer -notmatch '^[Yy]') {
                    warn "Skipped: settings.json"
                } else {
                    Copy-Item $settingsSrc $settingsDest -Force
                    Add-GitIgnore $ProjectPath $settingsDest
                    log "Installed settings.json (copied)"
                }
            }
        }
    } else {
        if (Test-Path $settingsDest) { Remove-Item $settingsDest -Force }
        Copy-Item $settingsSrc $settingsDest
        Add-GitIgnore $ProjectPath $settingsDest
        log "Installed settings.json (copied)"
    }

    # Install each type from defaults.conf
    foreach ($typeVar in @('COMMANDS','RULES','AGENTS','SKILLS')) {
        $typeDir = switch ($typeVar) {
            'COMMANDS' { 'commands' }
            'RULES'    { 'rules'    }
            'AGENTS'   { 'agents'   }
            'SKILLS'   { 'skills'   }
        }
        $items = $conf[$typeVar]
        if (-not $items -or $items.Count -eq 0) { continue }

        if ($items[0] -eq 'all') {
            Install-Type $ProjectPath $typeDir '' $Force
        } else {
            foreach ($item in $items) {
                Install-Type $ProjectPath $typeDir $item $Force
            }
        }
    }

    # Templates - symlink into both .github/ and .claude/templates/
    $templates = $conf['TEMPLATES']
    if ($templates -and $templates.Count -gt 0) {
        $ghDir       = Join-Path $ProjectPath '.github'
        $tmplDest    = Join-Path $target 'templates'
        $tmplSrcDir  = Join-Path $SCRIPT_DIR 'templates'
        $null = New-Item $ghDir    -ItemType Directory -Force
        $null = New-Item $tmplDest -ItemType Directory -Force

        $tmplFiles = if ($templates[0] -eq 'all') {
            Get-ChildItem $tmplSrcDir -Filter '*.md' -File
        } else {
            $templates | ForEach-Object { Get-Item (Join-Path $tmplSrcDir $_) -ErrorAction SilentlyContinue }
        }

        foreach ($tmpl in $tmplFiles) {
            if (-not $tmpl) { continue }
            $ghDest   = Join-Path $ghDir    $tmpl.Name
            $clDest   = Join-Path $tmplDest $tmpl.Name
            if (New-SymlinkFile $tmpl.FullName $ghDest $Force) { Add-GitIgnore $ProjectPath $ghDest }
            if (New-SymlinkFile $tmpl.FullName $clDest $Force) { Add-GitIgnore $ProjectPath $clDest }
            log "Installed template: $($tmpl.Name)"
        }
    }

    # Sync: remove symlinks pointing to this repo that are no longer in defaults
    $syncCount = 0
    foreach ($managedDir in @('rules','agents','commands','skills','templates')) {
        $d = Join-Path $target $managedDir
        if (-not (Test-Path $d)) { continue }

        Get-ChildItem $d -Recurse -File | Where-Object { $_.LinkType -eq 'SymbolicLink' } | ForEach-Object {
            $linkTarget = $_.Target
            if (-not $linkTarget.StartsWith($SCRIPT_DIR)) { return }

            $fname       = $_.Name
            $shouldExist = $false
            $items       = $conf[$managedDir.ToUpper()]

            if ($items -and $items[0] -eq 'all') {
                $shouldExist = $true
            } elseif ($items) {
                if ($managedDir -eq 'skills') {
                    $skillName = $_.FullName.Replace((Join-Path $target 'skills\'), '').Split('\')[0]
                    $shouldExist = $items -contains $skillName
                } elseif ($managedDir -eq 'rules') {
                    $rel = $_.FullName.Replace((Join-Path $target 'rules\'), '').Replace('\', '/')
                    $shouldExist = ($items -contains $fname) -or ($items -contains $rel)
                } else {
                    $shouldExist = $items -contains $fname
                }
            }

            if (-not $shouldExist) {
                Remove-Item $_.FullName -Force
                warn "Removed (not in defaults): $managedDir\$fname"
                $syncCount++
            }
        }
    }
    # Sync .github templates
    $ghDir = Join-Path $ProjectPath '.github'
    if (Test-Path $ghDir) {
        Get-ChildItem $ghDir -File | Where-Object { $_.LinkType -eq 'SymbolicLink' } | ForEach-Object {
            if (-not $_.Target.StartsWith($SCRIPT_DIR)) { return }
            $fname       = $_.Name
            $items       = $conf['TEMPLATES']
            $shouldExist = ($items -and $items[0] -eq 'all') -or ($items -contains $fname)
            if (-not $shouldExist) {
                Remove-Item $_.FullName -Force
                warn "Removed (not in defaults): .github\$fname"
                $syncCount++
            }
        }
    }
    if ($syncCount -gt 0) { log "Synced: removed $syncCount item(s) not in defaults.conf" }

    Write-Host ''
    log "Setup complete!"
    Write-Host "  Use -List to see available items."
    Write-Host "  Use -Add/-Remove to customize."
}

# ---------- List available items ----------
function Show-List {
    param([string]$Type = '')

    function List-Dir {
        param([string]$Dir, [string]$Label)
        $path = Join-Path $SCRIPT_DIR $Dir
        if (-not (Test-Path $path)) { return }
        Write-Host "`n$Label`:" -ForegroundColor White
        if ($Dir -eq 'skills') {
            Get-ChildItem $path -Directory | ForEach-Object { Write-Host "  $($_.Name)" }
        } else {
            Get-ChildItem $path -Filter '*.md' -File | ForEach-Object { Write-Host "  $($_.Name)" }
            Get-ChildItem $path -Directory | ForEach-Object {
                $sub = $_
                Get-ChildItem $sub.FullName -Filter '*.md' -File | ForEach-Object {
                    Write-Host "  $($sub.Name)/$($_.Name)"
                }
            }
        }
    }

    if (-not $Type) {
        List-Dir 'commands'  'Commands'
        List-Dir 'rules'     'Rules'
        List-Dir 'agents'    'Agents'
        List-Dir 'skills'    'Skills'
        List-Dir 'templates' 'Templates'
    } else {
        switch ($Type) {
            { $_ -in 'command',  'commands'  } { List-Dir 'commands'  'Commands'  }
            { $_ -in 'rule',     'rules'     } { List-Dir 'rules'     'Rules'     }
            { $_ -in 'agent',    'agents'    } { List-Dir 'agents'    'Agents'    }
            { $_ -in 'skill',    'skills'    } { List-Dir 'skills'    'Skills'    }
            { $_ -in 'template', 'templates' } { List-Dir 'templates' 'Templates' }
            default { err "Unknown type: $Type"; exit 1 }
        }
    }
}

# ---------- Interactive config wizard ----------
function Invoke-Config {
    header "Configure defaults.conf"
    Write-Host "  Select what gets installed by default."
    Write-Host "  Enter numbers separated by spaces, 'all', or press Enter to skip.`n"

    function Pick-Items {
        param([string]$Label, [string]$Dir)

        $path  = Join-Path $SCRIPT_DIR $Dir
        $items = @()
        if ($Dir -eq 'skills') {
            $items = @(Get-ChildItem $path -Directory | ForEach-Object { $_.Name })
        } else {
            $items  = @(Get-ChildItem $path -Filter '*.md' -File | ForEach-Object { $_.Name })
            $items += @(Get-ChildItem $path -Directory | ForEach-Object {
                $sub = $_
                Get-ChildItem $sub.FullName -Filter '*.md' -File | ForEach-Object { "$($sub.Name)/$($_.Name)" }
            })
        }

        if ($items.Count -eq 0) { return @() }

        Write-Host "`n$Label`:" -ForegroundColor White
        for ($i = 0; $i -lt $items.Count; $i++) {
            Write-Host ("  {0,2}) {1}" -f ($i+1), $items[$i])
        }

        $choice = Read-Host "  Choose (numbers/all/Enter to skip)"
        if (-not $choice)       { return @() }
        if ($choice -eq 'all')  { return @('all') }

        $selected = @()
        foreach ($num in $choice -split '\s+') {
            $idx = [int]$num - 1
            if ($idx -ge 0 -and $idx -lt $items.Count) {
                $selected += $items[$idx]
            }
        }
        return $selected
    }

    $conf = @{
        COMMANDS         = Pick-Items 'Commands' 'commands'
        RULES            = Pick-Items 'Rules'    'rules'
        AGENTS           = Pick-Items 'Agents'   'agents'
        SKILLS           = Pick-Items 'Skills'   'skills'
        TEMPLATES        = Pick-Items 'Templates''templates'
    }

    Write-Host ''
    $settingsAnswer = Read-Host "Install settings.json by default? [y/N]"
    $conf['INSTALL_SETTINGS'] = $settingsAnswer -match '^[Yy]'

    Write-Host ''
    Write-DefaultsConf $conf
    log "Saved defaults.conf"
    Write-Host ''
    Get-Content (Join-Path $SCRIPT_DIR 'defaults.conf') | ForEach-Object { Write-Host $_ }
}

# ============================================================
# ---------- Argument parsing ----------
# ============================================================

$ProjectPath  = ''
$Force        = $false
$SkipSettings = $false
$DoRemove     = $false
$RemoveType   = ''
$RemoveName   = ''
$AddType      = ''
$AddName      = ''
$DoList       = $false
$ListType     = ''
$DoConfig     = $false

$argList = [System.Collections.ArrayList]@($args)

if ($argList.Count -eq 0) {
    $ProjectPath = Read-Host "Project path"
    if (-not $ProjectPath) { Show-Usage }
    $ProjectPath = $ProjectPath -replace '^~', $HOME
}

$i = 0
while ($i -lt $argList.Count) {
    $arg = $argList[$i]
    switch -Regex ($arg) {
        '^(-Force|--force)$' {
            $Force = $true; break
        }
        '^(-SkipSettings|--skip-settings)$' {
            $SkipSettings = $true; break
        }
        '^(-Config|--config)$' {
            $DoConfig = $true; break
        }
        '^(-List|--list)$' {
            $DoList = $true
            if (($i+1) -lt $argList.Count -and $argList[$i+1] -match '^(rules?|agents?|commands?|skills?|templates?)$') {
                $i++; $ListType = $argList[$i]
            }
            break
        }
        '^(-Remove|--remove)$' {
            $DoRemove = $true
            if (($i+1) -lt $argList.Count -and $argList[$i+1] -match '^(rules?|agents?|commands?|skills?)$') {
                $i++; $RemoveType = Get-TypeDir $argList[$i]
                if (($i+1) -lt $argList.Count -and $argList[$i+1] -notmatch '^-') {
                    $i++; $RemoveName = $argList[$i]
                }
            }
            break
        }
        '^(-Add|--add)$' {
            if (($i+1) -ge $argList.Count) { err "-Add requires a type"; Show-Usage }
            $i++; $AddType = Get-TypeDir $argList[$i]
            if (($i+1) -lt $argList.Count -and $argList[$i+1] -notmatch '^-') {
                $i++; $AddName = $argList[$i]
            }
            break
        }
        '^(-Help|--help|-h)$' { Show-Usage }
        '^-' { err "Unknown flag: $arg"; Show-Usage }
        default {
            if (-not $ProjectPath) {
                $ProjectPath = $arg -replace '^~', $HOME
            } else {
                err "Unexpected argument: $arg"; Show-Usage
            }
            break
        }
    }
    $i++
}

# ---------- Execute ----------

if ($DoConfig) {
    Invoke-Config
    $answer = Read-Host "`nRun setup now? Enter project path (or Enter to skip)"
    if ($answer) {
        $ProjectPath = $answer -replace '^~', $HOME
    } else {
        exit 0
    }
}

if ($DoList) {
    Show-List $ListType
    exit 0
}

# Prompt for path if still missing
if (-not $ProjectPath) {
    $ProjectPath = Read-Host "Project path"
    $ProjectPath = $ProjectPath -replace '^~', $HOME
    if (-not $ProjectPath) { err "Project path required"; Show-Usage }
}

if (-not (Test-Path $ProjectPath -PathType Container)) {
    err "Project path not found: $ProjectPath"
    exit 1
}

Warn-SymlinkCapability

if ($DoRemove) {
    Remove-Items $ProjectPath $RemoveType $RemoveName
    exit 0
}

if ($AddType) {
    Install-Type $ProjectPath $AddType $AddName $Force
    exit 0
}

Install-Default $ProjectPath $Force $SkipSettings
